name: Release

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.x'

      - name: Build
        run: dotnet build --configuration Release Validator
        working-directory: src

      - name: Create the package
        run: dotnet pack --configuration Release Validator /p:Version=${{ github.event.release.tag_name }} /p:ContinuousIntegrationBuild=true
        working-directory: src

      - name: Publish the package to nuget.org
        run: dotnet nuget push Validator/bin/Release/*.nupkg --api-key ${{ secrets.NUGET_API_SECRET }} --source https://api.nuget.org/v3/index.json
        working-directory: src
